### ISSUE TITLE
Update packagist package to support laravel 5.5

### ISSUE THREAD

**Issue by Henokv** [laravel-notification-channels/plivo#22] opened 2017-11-22 18:55 UTC
Just noticed the repo now supports laravel 5.5 but packagist still only accepts 5.4.
Could you add a new release so the package will be compatible with 5.5? @koomai

**Comment by koomai** [comment] 2017-12-05 13:25
Unfortunately, I don't have access to packagist for this github repo. It seemed like a good idea first, but I might as well have maintained this under my own account.

**Comment by cayaner** [comment] 2017-12-07 08:16
Any Update!

**Comment by Henokv** [comment] 2017-12-13 10:34
Hi,
Normally you should be able to update packagist by adding a release version (semantic version) tag to your repo.
It should update on packagist.

**Comment by koomai** [comment] 2017-12-14 03:56
Had the same issue before with not auto-updating. Tagging hasn't helped. Need to force an update on Packagist and I don't have access.

**Comment by koomai** [comment] 2017-12-14 03:57
Duplicate of #20

**Closed by koomai** 2017-12-14 03:56 UTC
